name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
          token: ${{ secrets.TOKEN }}
          submodules: recursive
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/azalea-w/plza-se-web:latest
      
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u "azalea-w" --password-stdin
      
    - name: Push Docker image
      run: docker push ghcr.io/azalea-w/plza-se-web:latest
